name: Specific setup for whirl
description: Installs Quarto and enables strace on Linux
runs:
  using: "composite"
  steps:
    - name: Allow strace to attach to a process
      if: runner.os == 'Linux'
      shell: bash
      run: |
        echo 0 | sudo tee /proc/sys/kernel/yama/ptrace_scope
        sudo setcap cap_sys_ptrace=eip /usr/bin/strace

    - name: Install Quarto
      uses: quarto-dev/quarto-actions/setup@v2

    - name: (Linux) Install Python requirements and dependencies
      if: runner.os == 'Linux'
      shell: bash
      run: |
        python3 -m pip install jupyter
        python3 -m pip install pandas
        python3 -m pip install numpy

    - name: (macOS) Install Python requirements and dependencies
      if: runner.os == 'macOS'
      shell: bash
      run: |
        brew install jupyter
        python3 -m pip install pandas
        python3 -m pip install numpy

    - name: (Windows) Install Python requirements and dependencies
      if: runner.os == 'Windows'
      shell: bash
      run: |
        py -m pip install jupyter
        py -m pip install pandas
        py -m pip install numpy
