name: Specific setup for whirl
description: Installs Quarto and enables strace on Linux
runs:
  using: "composite"
  steps:
    - name: Allow strace to attach to a process
      if: runner.os == 'Linux'
      shell: bash
      run: |
        echo 0 | sudo tee /proc/sys/kernel/yama/ptrace_scope
        sudo setcap cap_sys_ptrace=eip /usr/bin/strace

    - name: Install Quarto
      uses: quarto-dev/quarto-actions/setup@v2

    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v7

    - name: Install python packages based on pyproject.toml
      shell: bash
      run: |
        uv sync

    - name: Set virtual env for reticulate (not windows)
      if: runner.os != 'Windows'
      shell: bash
      run: |
        echo "VIRTUAL_ENV=$PWD/.venv" >> $GITHUB_ENV

    - name: Set virtual env for reticulate (windows)
      if: runner.os == 'Windows'
      shell: bash
      run: |
        echo "VIRTUAL_ENV=$PWD/.venv" | Out-File -FilePath $env:GITHUB_ENV -Append

