name: Specific setup for whirl
description: Installs Quarto and enables strace on Linux
runs:
  using: "composite"
  steps:
    - name: Allow strace to attach to a process
      if: runner.os == 'Linux'
      shell: bash
      run: |
        echo 0 | sudo tee /proc/sys/kernel/yama/ptrace_scope

    - name: Install Quarto
      uses: quarto-dev/quarto-actions/setup@v2

    - name: (Linux) Install jupyter
      if: runner.os == 'Linux'
      shell: bash
      run: python3 -m pip install jupyter

    - name: (macOS) Install jupyter via Homebrew
      if: runner.os == 'macOS'
      shell: bash
      run: |
        brew install jupyter
        # Verify installation
        python3 -c "import jupyter; print('Jupyter installed successfully')"


    - name: (Windows) Install jupyter
      if: runner.os == 'Windows'
      shell: bash
      run: py -m pip install jupyter
