---
# This is a YAML configuration file
# It contains parameters for the application
params:
  # A character vector of file paths to R, R Markdown, or Quarto scripts
  paths  : ["prg1.R", "prgRmd.Rmd"]
  # Enable parallel processing
  parallel : TRUE
  # Number of CPU cores to use (set to null for default)
  num_cores : NULL
  # Directory for summary output
  summary_dir: "."
  # Track files during execution
  track_files: TRUE
  # Check the runtime environment
  check_renv: TRUE
  # Output formats (set to null for html default)
  out_formats: NULL
  # Folder for approved packages
  approved_pkgs_folder: NULL
  # URL for approved packages
  approved_pkgs_url: NULL
  # Output directory
  out_dir: "."
---
